<?php

declare(strict_types=1);

use App\Controllers\Admin\DashboardController;
use App\Controllers\Admin\EducationActivityController;
use App\Controllers\Admin\MunicipalityMediaController;
use App\Controllers\Admin\MunicipalityController as AdminMunicipalityController;
use App\Controllers\Admin\PointOfInterestController as AdminPointOfInterestController;
use App\Controllers\Admin\QuizController as AdminQuizController;
use App\Controllers\Admin\QuizQuestionController as AdminQuizQuestionController;
use App\Controllers\Admin\StateController;
use App\Controllers\Admin\CurationController;
use App\Controllers\AuthController;
use App\Controllers\EducationController;
use App\Controllers\HomeController;
use App\Controllers\MediaController;
use App\Controllers\MunicipalityController;
use App\Controllers\MyMapiController;
use App\Controllers\PointOfInterestController;
use App\Controllers\QuizController;
use App\Controllers\QrCodeController;
use App\Controllers\SearchController;
use App\Controllers\SetupController;
use App\Middleware\AdminMiddleware;
use App\Middleware\AuthMiddleware;
use App\Middleware\GuestMiddleware;

$router->get('', [HomeController::class, 'index']);
$router->get('instalacao', [SetupController::class, 'show']);
$router->get('entrar', [AuthController::class, 'showLogin'], [GuestMiddleware::class]);
$router->post('entrar', [AuthController::class, 'login'], [GuestMiddleware::class]);
$router->post('sair', [AuthController::class, 'logout'], [AuthMiddleware::class]);
$router->get('meu-mapi', [MyMapiController::class, 'index'], [AuthMiddleware::class]);
$router->get('mapi-educacao', [EducationController::class, 'index']);
$router->get('mapi-educacao/atividade/{id}', [EducationController::class, 'show']);
$router->get('busca', [SearchController::class, 'index']);
$router->get('mapa', [MunicipalityController::class, 'map']);
$router->get('municipios', [MunicipalityController::class, 'index']);
$router->get('municipio/{slug}', [MunicipalityController::class, 'show']);
$router->get('turismo/{id}', [PointOfInterestController::class, 'show']);
$router->get('midia/{id}', [MediaController::class, 'show']);
$router->get('qrcode/municipio/{slug}', [QrCodeController::class, 'municipality']);
$router->post('municipio/{slug}/favorito', [MunicipalityController::class, 'toggleFavorite'], [AuthMiddleware::class]);
$router->post('municipio/{slug}/visitado', [MunicipalityController::class, 'toggleVisited'], [AuthMiddleware::class]);
$router->get('api/municipios-mapa', [MunicipalityController::class, 'markers']);
$router->get('quiz/{id}', [QuizController::class, 'show']);
$router->post('quiz/{id}/responder', [QuizController::class, 'submit']);
$router->get('ranking', [QuizController::class, 'ranking']);

$router->get('admin', [DashboardController::class, 'index'], [AdminMiddleware::class]);
$router->get('admin/estados', [StateController::class, 'index'], [AdminMiddleware::class]);
$router->get('admin/estados/novo', [StateController::class, 'create'], [AdminMiddleware::class]);
$router->post('admin/estados', [StateController::class, 'store'], [AdminMiddleware::class]);
$router->post('admin/estados/importar-ibge', [StateController::class, 'import'], [AdminMiddleware::class]);
$router->get('admin/estados/{id}/editar', [StateController::class, 'edit'], [AdminMiddleware::class]);
$router->post('admin/estados/{id}', [StateController::class, 'update'], [AdminMiddleware::class]);

$router->get('admin/municipios', [AdminMunicipalityController::class, 'index'], [AdminMiddleware::class]);
$router->get('admin/municipios/novo', [AdminMunicipalityController::class, 'create'], [AdminMiddleware::class]);
$router->post('admin/municipios', [AdminMunicipalityController::class, 'store'], [AdminMiddleware::class]);
$router->post('admin/municipios/importar-ibge', [AdminMunicipalityController::class, 'import'], [AdminMiddleware::class]);
$router->post('admin/municipios/importar-dados-ibge', [AdminMunicipalityController::class, 'importFacts'], [AdminMiddleware::class]);
$router->post('admin/municipios/publicar-em-massa', [AdminMunicipalityController::class, 'bulkPublish'], [AdminMiddleware::class]);
$router->post('admin/municipios/base-editorial-em-massa', [AdminMunicipalityController::class, 'bulkGenerateEditorialBase'], [AdminMiddleware::class]);
$router->get('admin/municipios/{id}/editar', [AdminMunicipalityController::class, 'edit'], [AdminMiddleware::class]);
$router->post('admin/municipios/{id}', [AdminMunicipalityController::class, 'update'], [AdminMiddleware::class]);
$router->post('admin/municipios/{id}/gerar-base-editorial', [AdminMunicipalityController::class, 'generateEditorialBase'], [AdminMiddleware::class]);
$router->post('admin/municipios/{id}/workflow/enviar-revisao', [AdminMunicipalityController::class, 'submitForReview'], [AdminMiddleware::class]);
$router->post('admin/municipios/{id}/workflow/em-correcao', [AdminMunicipalityController::class, 'requestCorrection'], [AdminMiddleware::class]);
$router->post('admin/municipios/{id}/workflow/aprovar', [AdminMunicipalityController::class, 'approve'], [AdminMiddleware::class]);
$router->post('admin/municipios/{id}/workflow/reprovar', [AdminMunicipalityController::class, 'reject'], [AdminMiddleware::class]);
$router->post('admin/municipios/{id}/workflow/publicar', [AdminMunicipalityController::class, 'publish'], [AdminMiddleware::class]);
$router->post('admin/municipios/{id}/workflow/arquivar', [AdminMunicipalityController::class, 'archive'], [AdminMiddleware::class]);
$router->get('admin/municipios/{id}/qrcode', [\App\Controllers\Admin\QrCodeController::class, 'showMunicipality'], [AdminMiddleware::class]);

$router->get('admin/curadoria', [CurationController::class, 'index'], [AdminMiddleware::class]);
$router->get('admin/educacao', [EducationActivityController::class, 'index'], [AdminMiddleware::class]);
$router->get('admin/educacao/nova', [EducationActivityController::class, 'create'], [AdminMiddleware::class]);
$router->post('admin/educacao', [EducationActivityController::class, 'store'], [AdminMiddleware::class]);
$router->get('admin/educacao/{id}/editar', [EducationActivityController::class, 'edit'], [AdminMiddleware::class]);
$router->post('admin/educacao/{id}', [EducationActivityController::class, 'update'], [AdminMiddleware::class]);
$router->get('admin/turismo', [AdminPointOfInterestController::class, 'index'], [AdminMiddleware::class]);
$router->get('admin/turismo/novo', [AdminPointOfInterestController::class, 'create'], [AdminMiddleware::class]);
$router->post('admin/turismo', [AdminPointOfInterestController::class, 'store'], [AdminMiddleware::class]);
$router->get('admin/turismo/{id}/editar', [AdminPointOfInterestController::class, 'edit'], [AdminMiddleware::class]);
$router->post('admin/turismo/{id}', [AdminPointOfInterestController::class, 'update'], [AdminMiddleware::class]);
$router->get('admin/midias', [MunicipalityMediaController::class, 'index'], [AdminMiddleware::class]);
$router->get('admin/midias/automacao', [MunicipalityMediaController::class, 'automationReport'], [AdminMiddleware::class]);
$router->get('admin/midias/cobertura', [MunicipalityMediaController::class, 'coverageReport'], [AdminMiddleware::class]);
$router->get('admin/midias/descobrir', [MunicipalityMediaController::class, 'discoverCandidates'], [AdminMiddleware::class]);
$router->get('admin/midias/descobrir-lote', [MunicipalityMediaController::class, 'discoverBatch'], [AdminMiddleware::class]);
$router->post('admin/midias/descobrir-lote/importar', [MunicipalityMediaController::class, 'importDiscoveryBatch'], [AdminMiddleware::class]);
$router->get('admin/midias/nova', [MunicipalityMediaController::class, 'create'], [AdminMiddleware::class]);
$router->get('admin/midias/importar-wikimedia', [MunicipalityMediaController::class, 'importForm'], [AdminMiddleware::class]);
$router->get('admin/midias/importar-lote-wikimedia', [MunicipalityMediaController::class, 'bulkImportForm'], [AdminMiddleware::class]);
$router->post('admin/midias', [MunicipalityMediaController::class, 'store'], [AdminMiddleware::class]);
$router->post('admin/midias/importar-wikimedia', [MunicipalityMediaController::class, 'importFromWikimedia'], [AdminMiddleware::class]);
$router->post('admin/midias/importar-lote-wikimedia', [MunicipalityMediaController::class, 'bulkImportFromWikimedia'], [AdminMiddleware::class]);
$router->get('admin/midias/{id}/editar', [MunicipalityMediaController::class, 'edit'], [AdminMiddleware::class]);
$router->post('admin/midias/{id}', [MunicipalityMediaController::class, 'update'], [AdminMiddleware::class]);
$router->get('admin/quizzes', [AdminQuizController::class, 'index'], [AdminMiddleware::class]);
$router->get('admin/quizzes/novo', [AdminQuizController::class, 'create'], [AdminMiddleware::class]);
$router->post('admin/quizzes', [AdminQuizController::class, 'store'], [AdminMiddleware::class]);
$router->get('admin/quizzes/{id}/editar', [AdminQuizController::class, 'edit'], [AdminMiddleware::class]);
$router->post('admin/quizzes/{id}', [AdminQuizController::class, 'update'], [AdminMiddleware::class]);
$router->get('admin/quizzes/{quiz_id}/perguntas', [AdminQuizQuestionController::class, 'index'], [AdminMiddleware::class]);
$router->get('admin/quizzes/{quiz_id}/perguntas/nova', [AdminQuizQuestionController::class, 'create'], [AdminMiddleware::class]);
$router->post('admin/quizzes/{quiz_id}/perguntas', [AdminQuizQuestionController::class, 'store'], [AdminMiddleware::class]);
$router->get('admin/quizzes/{quiz_id}/perguntas/{id}/editar', [AdminQuizQuestionController::class, 'edit'], [AdminMiddleware::class]);
$router->post('admin/quizzes/{quiz_id}/perguntas/{id}', [AdminQuizQuestionController::class, 'update'], [AdminMiddleware::class]);
